version: '3'

services:
  cubetechsmswrapper:
    build: .
    command: "npm run dev"
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/cubetechsmswrapper
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
